### ISSUE TITLE
[BUG] Медленный WiFi

### ISSUE THREAD

**Issue by ghost** [Sergey1560/Marlin_FB4S#44]
ОЧЕНЬ медленно передаются файлы на печать из Cura. В родную прошивку всё заливается гораздо веселее.

**Comment by FialDrag** [comment]
У меня вообще при заливке через вай-фай с этой версией 2.0.9.1 СД-карта отваливается в 95% случаев, хотя с самой карты (уже со скинутым файлом) печатает без проблем. Вернулся на 2.0.7.2, там все работает отлично.

**Comment by 3DAngel10** [comment]
In this version (2.0.9.1) the download of the files (wifi via Cura) stops and the screen goes black. Pulling out the SD card shows you again. Another bug is that the cooling fan does not start on power up for a few ms as in version 2.0.8.1

**Comment by Sergey1560** [comment]
@MasteHiggins @FialDrag  в 2.0.9 сменился слой абстракции с libmaple на HAL от ST. После этого появились проблемы с передачей файлов. На данный момент не понятна причина проблем и готового решения нет. Используйте 2.0.7.2, она наиболее стабильная из последних версий. Ничего принципиального нового в 2.0.9 нет.

@3DAngel10 Since version 2.0.9 there are problems with file transfer. The problem is not solved yet, use 2.0.7.2 as the most stable one. 
What's the problem with the fans not jerking when turned on? Why do you need this?

**Comment by 3DAngel10** [comment]
#define FAN_KICKSTART_TIME 100 in version 2.0.8.1 works and in this new one no, it's just to let you know (although you will surely know about it) not that I need it. Anyway you are doing a great job congratulations :)

**Comment by ghost** [comment]
@Sergey1560 да, 2.0.7.2 поинтересней. Немного криво срабатывают нижние стрелки перемещения по меню (подозреваю, что по этой причине в 2.0.8.1 и была добавлена калибровка), но в целом - ОК.
Спасибо большое!

**Comment by Sergey1560** [comment]
Все проблемы с картой тут https://github.com/Sergey1560/Marlin_FB4S/issues/49
